config/routes.rb
Rails.application.routes.draw do

  devise_for :dogs, skip: [:passwords], path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "signup"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :woofs
  has_many :followers, class_name: "Follow", foreign_key: "follower_id"
  has_many :followings, class_name: "Follow", foreign_key: "following_id"
  validates :username, presence: true, uniqueness: true, length: { minimum: 8 }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "Dog"
  belongs_to :following, class_name: "Dog"
end

app/models/woof.rb
class Woof < ApplicationRecord
  belongs_to :dog
  belongs_to :rewoof, class_name: "Woof", optional: true
  validate :no_content, :too_much_content

  def original_dog
    rewoof ? rewoof.dog : dog
  end

  private
  def no_content
    if text.nil? && rewoof_id.nil?
      errors.add(:rewoof_id, "must exist if there is no text")
      errors.add(:text, "must exist if it is not a rewoof")
    end
  end

  def too_much_content
    if !text.nil? && !rewoof_id.nil?
      errors.add(:rewoof_id, "cannot exist if there is text")
      errors.add(:text, "cannot exist if it is a rewoof")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_dog!, except: [:signup, :login, :landing]
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
    if current_dog
      @woofs = Woof.all
      render :home
    else
      render :landing
    end
  end
end

app/views/home/home.html.erb
<p>HOME</p>
<% @woofs.each do |w| %>
  <% @woof = w %>
  <%= render "partials/woof" %>
<% end %>

app/views/home/index.html.erb
<p>Welcome!</p>

app/views/home/landing.html.erb
<%= link_to "Login", new_dog_session_path %>
<%= link_to "Sign Up", new_dog_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wuffer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="nav-bar">
      <h1>Wüffer</h1>
      <% if current_dog %>
        <%= button_to "Logout", destroy_dog_session_path, method: :delete %>
      <% end %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_woof.html.erb
<p><%= @woof.text %></p>